# Generated by Django 6.0.4 on 2026-04-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
